language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script: npm test
deploy:
  provider: npm
  email: mariosant@sent.com
  on:
    branch: master
    tags: true
  api_key:
    secure: J6mM6TKTM2w+IMurlS62m+xMBKyk0DAPBAhoVLrPWhe7lpM2QNAFVzbWDBAsLbHFiOXiarh/3Nmo0jdaeCEPsbZ/Kf7VSIWB2s4iKd9v5fEXH8pIkzNkO/ADY86UXJy/NX9nbyozHdyBuH1BuvhGW4ymO4uD2F4okjHlP2DSOdMJzZ2PxDxaG8QpRbX2xmQxxqHi9yK7c6x4py7Xu1tJzBPpjsQI2cBOsmmBkBjX6GwyCBHanZxmwLJabVTt8j4A3jgvcRF9QHTBEyhGpzf33sRkdZ1w2D72k0veZxYPLWJyCP41E0GhwNu5YUNj9u6RVqbUyog5dtPkZdDUi8Yj3393XQqncFAQgBl6V/h+JLFW19c7nh+ri2fipGzvi500M1zMteuObdYrYTackmTHYiQ1oMDDG+KW3e1FPBqNEKh3vUez7rW+Zfmr/Uxp4Ga1DoVv8YtPEBiKoycQ5nMIRuaF/gfZmfWeZwypA8d8lRqn+4NvT/d3tbwp/mQqJvBwHZ0j8xX2pCgLtwS0KD6K4nWnjH5xJtSrgkdSf85Y4IVddsZptCpt0D2OfK6jvy/A1YHpO2Aw+hQK/9S0Rop64Cvzmket8tE0s4n/1tn2KxJZobTuf9aa66pTV+sc9J23v9zATalYMA2cJl3bOkrATXftazjr9bUNqPwK79NrFFQ=
